In [39]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd

In [40]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [41]:
print("iris_dataset의 키 : \n{}".format(iris_dataset.keys()))

iris_dataset의 키 : 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [42]:
print(iris_dataset['DESCR'][:193] + "\n...") # DESCR 키에는 데이터셋에 대한 간략한 설명이 들어있음

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive att
...


In [43]:
print("타깃의 이름 :\n{}".format(iris_dataset['target_names']))

타깃의 이름 :
['setosa' 'versicolor' 'virginica']


In [44]:
print("특성의 이름 :\n{}".format(iris_dataset['feature_names'])) 

특성의 이름 :
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [45]:
print("data의 이름 :\n{}".format(type(iris_dataset['data'])))

data의 이름 :
<class 'numpy.ndarray'>


In [46]:
print("data의 크기 :\n{}".format(iris_dataset['data'].shape))

data의 크기 :
(150, 4)


In [47]:
print("data의 처음 다섯 행 :\n{}".format(iris_dataset['data'][:5]))

data의 처음 다섯 행 :
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [48]:
print("target의 타입 :\n{}".format(type(iris_dataset['target'])))

target의 타입 :
<class 'numpy.ndarray'>


In [49]:
print("target의 크기 :\n{}".format(iris_dataset['target'].shape))

target의 크기 :
(150,)


In [50]:
print("타깃:\n{}".format(iris_dataset['target']))

타깃:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=0)

In [52]:
print("X_train 크기 : {}".format(X_train.shape))

X_train 크기 : (112, 4)


In [53]:
print("y_train 크기 : {}".format(y_train.shape))

y_train 크기 : (112,)


In [54]:
print("X_test 크기 : {}".format(X_test.shape))
print("Y_test 크기 : {}".format(y_test.shape))

X_test 크기 : (38, 4)
Y_test 크기 : (38,)


In [55]:
print("x_train : {}".format(X_train[:5]))
print("y_train : {}".format(y_train[:5]))

x_train : [[5.9 3.  4.2 1.5]
 [5.8 2.6 4.  1.2]
 [6.8 3.  5.5 2.1]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.1 2.3]]
y_train : [1 1 2 0 2]


In [56]:
#X_train 데이터를 사용해서 데이터프레임을 만듭니다.
#열의 이름은 iris_dataset.feature_names에 있는 문자열을 사용합니다.
import pandas as pd
iris_dataframe = pd.DataFrame(X_train, columns=iris_dataset.feature_names)
#데이터프레임을 사용해 y_train에 따라 색으로 구분된 산점도 행렬을 만듭니다.
pd.plotting.scatter_matrix(iris_dataframe, c=y_train, figsize=(15,15), marker='0', hist_kwds={'bins' : 20}, s=60, alpha=.8, cmap=mglearn.cm3)

NameError: name 'mglearn' is not defined