In [1]:
import numpy as np

In [3]:
x = np.array([[1,2],[3,4]])

In [4]:
print(np.sum(x))

10


In [11]:
np.sum(x, axis=0) # 각 열에 대한 연산 axis =0

array([4, 6])

In [8]:
np.sum(x, axis=1) # 각 행에 대한 연산 axis =1

array([3, 7])

In [12]:
## 브로드 캐스팅
# numpy에서 shape가 다른 배열 간에도 산술 연산이 가능하게 하는 메커니즘
# 종종 큰 배열을 대상으로 작은 배열을 여러번 연산하고자 할 때가 있음
# 예를 들어 행렬의 각 행에 상수 벡터를 더하는 것

# 행렬 x의 각 행에 벡터 v를 더한 뒤, 그 결과를 행렬 y에 저장
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [19]:
v = np.array([1, 0, 1])
y = np.empty_like(x)

In [20]:
print(x); 
print(v);
print(y);

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
[[-1277575612     2141744  -820788852]
 [ -946798560  -951794235  -913768416]
 [    2147036 -1194539452  -910109352]
 [-1162149856 -1028270712 -1293634872]]


In [24]:
# 명시적 반복문을 통해 행렬 x의 각 행에 벡터 v를 더하는 방법
for i in range(4): y[i, :] = x[i, :] + v

In [25]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [26]:
print(x[0, :]);

[1 2 3]


In [27]:
print(x[0:1,:]);

[[1 2 3]]


In [34]:
## 명시적 반복문은 성능이 느려질 수 있다.
## 벡터 'v'를 행렬 'x'의 각 행에 더하는 것은 'v'를 여러 개 복사해 수직으로 쌓은 행렬 'vv'를 만들고 이  'vv'를 'x'에 더하는것과 동일
vv = np.tile(v, (4,1)) # v의 복사본 4개를 위로 더한것

In [35]:
vv

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [36]:
y = x+vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [39]:
## Numpy 브로드캐스팅을 이용한다면 이렇게 v의 복사본을 만들지 않아도 동일한 연산을 할 수 있음.
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x+v # 브로드캐스팅을 이용하여 v를 x의 각 행에 더하기
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
